Set http.route attribute as path template
micronaut-projects/micronaut-tracing pull request #149
Opened 2022-08-15 11:41 UTC by StevenPJ

We have seen issues with the current spans exported from the http
library in observability backends, due to too granular span names when
the routes contain path variables.

As per the opentelemetry specification, this PR extracts the path
template from the UriRouteMatch object, and sets it as the
`http.route` attribute.

https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/http/#http-server-semantic-conventions

2022-08-16 10:31 UTC, StevenPJ commented
appreciate any feedback @sdelamo

2022-09-16 12:27 UTC, n0tl3ss approved these changes

2022-09-21 05:13 UTC, sdelamo requested changes

2022-09-21 05:13 UTC, sdelamo commented on tracing-opentelemetry-http/src/main/java/io/micronaut/tracing/opentelemetry/instrument/http/server/MicronautHttpServerAttributesGetter.java
> +            .filter(ri -> ri instanceof UriRouteMatch)
```suggestion
            .filter(UriRouteMatch.class::isInstance)
```

2022-10-14 10:18 UTC, merged