Use new propagation context API
micronaut-projects/micronaut-tracing pull request #281
Opened 2023-04-26 00:25 UTC by dstepanov

2023-05-17 17:27 UTC, dstepanov commented
The build is failing locally with:
```
  
  Message: No bean of type [io.grpc.ManagedChannel] exists for the given qualifier: @Named('grpc-server'). Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
  Path Taken: OpenTelemetryGrpcClientSpec.setTestBean([TestBean testBean]) --> TestBean.setBlockingStub([GreeterBlockingStub blockingStub]) --> Clients.blockingStub([Channel channel])
      at app//io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2322)
      at app//io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
```

2023-05-19 09:06 UTC, graemerocher requested changes

2023-05-19 09:06 UTC, graemerocher commented on tracing-brave-http/src/main/java/io/micronaut/tracing/brave/http/BraveTracingServerFilter.java
> +//            }
delete this code if it is not needed

2023-05-19 09:06 UTC, graemerocher commented on tracing-brave-http/src/main/resources/META-INF/native-image/io.micronaut.tracing/tracing-zipkin/native-image.properties
> +Args = --initialize-at-run-time=io.micronaut.tracing.brave.http.HttpTracingFactor
this file can be deleted

2023-05-19 09:06 UTC, graemerocher commented on tracing-brave-http/src/test/groovy/io/micronaut/tracing/brave/BraveTracerFactorySpec.groovy
> -    void 'test brace tracer report spans'() {
why was this test deleted?

2023-05-19 09:06 UTC, graemerocher commented on tracing-brave/src/main/resources/META-INF/native-image/io.micronaut.tracing/tracing-zipkin/native-image.properties
> +Args = --initialize-at-run-time=io.micronaut.tracing.brave.BraveTracerFactory,io.micronaut.tracing.brave.log.Slf4jCurrentTraceContextFactory,io.micronaut.tracing.brave.sender.HttpClientSenderFactory
this file can be deleted

2023-05-19 09:06 UTC, graemerocher commented on tracing-brave-http/src/test/groovy/io/micronaut/tracing/brave/BraveTracerFactorySpec.groovy
> -    void 'test brace tracer report spans'() {
Ok I see it was moved

2023-05-22 11:23 UTC, n0tl3ss commented on tracing-jaeger/src/test/groovy/io/micronaut/tracing/jaeger/HttpTracingSpec.groovy
> +//                        assert spanCustomizer.activeSpan()?.getBaggageItem('foo') == 'bar'
Does this validation needs to be present or deleted?

2023-05-22 11:23 UTC, n0tl3ss commented on tracing-jaeger/src/test/groovy/io/micronaut/tracing/jaeger/HttpTracingSpec.groovy
> +//            assert spanCustomizer.activeSpan()?.getBaggageItem('foo') == 'bar'
Does this validation needs to be present or deleted?

2023-05-22 13:22 UTC, merged